plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin.defaultRefmapName="${mod_id}.refmap.json"
    runs {
        gameTest {
            server()
            vmArg "-Dfabric-api.gametest=1"
        }

        xplatDatagen {
            client()
            vmArg "-Dextrabotany.xplat_datagen=1"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=extrabotany"
            vmArg "-Dfabric-api.datagen.output-dir=${file("../common/src/generated/resources")}"
        }

        fabricDatagen {
            client()
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=extrabotany"
            vmArg "-Dfabric-api.datagen.output-dir=${file("src/generated/resources")}"
        }

        configureEach {
            runDir "../run"
            ideConfigGenerated(true)
        }
    }
}

repositories {
    maven {
        name = "Modmuss"
        url = "https://maven.modmuss50.me/"
    }
    maven {
        name = "Ladysnake Libs"
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        name = "BuildCraft" // for LBA
        url = "https://mod-buildcraft.com/maven"
    }
    maven {
        name = "ParchmentMC"
        url = "https://maven.parchmentmc.net/"
    }
    maven { url = "https://maven.shedaniel.me" }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"

    modImplementation("vazkii.botania:botania-fabric-1.21.1:$botania_version")

    modImplementation "vazkii.patchouli:Patchouli:${patchouli_version}-FABRIC"

    compileOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"
    //modLocalRuntime "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"

    compileOnly "dev.emi:emi-fabric:${emi_version}:api"
    modLocalRuntime "dev.emi:emi-fabric:${emi_version}"

    // Don't include base and entity as Trinkets includes it already
    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${cca_version}"
    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${cca_version}"

    modImplementation("dev.emi:trinkets:${trinkets_version}") { transitive = false }

    modCompileOnly("maven.modrinth:sodium:mc${minecraft_version}-${sodium_version}-fabric") { transitive = false }
    modLocalRuntime("maven.modrinth:sodium:mc${minecraft_version}-${sodium_version}-fabric") { transitive = false }

    compileOnly("org.jetbrains:annotations:26.1.0")
}